### ISSUE TITLE
proposal: Separating Leaders

### ISSUE THREAD

**Issue by Xuanwo** [beyondstorage/community#26]
Now we have leader groups for all projects which are not needed, maybe we can merge them into one which responsible for the whole BeyondStorage community.

Inside these changes, we will

- Remove all leaders groups include `go-storage-leaders`, `beyond-tp-leaders`, `community-leaders`
- Add new group `leaders` which will have `admin` permissions on all BeyondStorage repos.
- Remove separate `community` teams
- All team members will have the same permissions on `site`

**Comment by Xuanwo** [comment]
ping all maintainer, committer and reviewers for advice.

@beyondstorage/beyond-tp-maintainer
@beyondstorage/beyond-tp-committer 
@beyondstorage/beyond-tp-reviewer 
@beyondstorage/go-storage-maintainer 
@beyondstorage/go-storage-committer 
@beyondstorage/go-storage-reviewer 
@beyondstorage/community-maintainer 
@beyondstorage/community-committer 
@beyondstorage/community-reviewer

**Comment by Prnyself** [comment]
I agree.
In some aspects, leader's permission is overlaped with maintainer. So, with the existence of maintainer, we may not need a higher permission role in each project.
